# Cloud Build configuration for Telegram Reminder Bot (Final & Stable Version)
# - Deploys the service with no traffic first to establish the URL.
# - Updates the service with its own URL.
# - Routes all traffic to the new, healthy revision.
# - Sets the Telegram webhook and performs a final health check.

steps:
  # 1) Build image (No changes)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/telegram-reminder-bot:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/telegram-reminder-bot:latest', '.']
    env: ['DOCKER_BUILDKIT=1']

  # 2) Push image (No changes)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/telegram-reminder-bot']
    waitFor: ['build-image']

# 3) Deploy to Cloud Run WITHOUT traffic
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloudrun'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'telegram-reminder-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/telegram-reminder-bot:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--no-traffic'
      - '--set-env-vars'
      # --- START OF CORRECTION ---
      # The name on the left is what the app sees (no underscore).
      # The value on the right is from the build trigger (with underscore).
      - >
        NODE_ENV=production,
        TZ=Asia/Bangkok,
        GOOGLE_CLOUD_REGION=asia-southeast1,
        TIDB_HOST=${_TIDB_HOST},
        TIDB_PORT=${_TIDB_PORT},
        TIDB_USER=${_TIDB_USER},
        TIDB_PASSWORD=${_TIDB_PASSWORD},
        TIDB_DATABASE=${_TIDB_DATABASE},
        TIDB_ENABLE_SSL=${_TIDB_ENABLE_SSL},
        LOG_LEVEL=${_LOG_LEVEL},
        LOG_TO_FILE=${_LOG_TO_FILE},
        TELEGRAM_BOT_TOKEN=${_TELEGRAM_BOT_TOKEN},
        TELEGRAM_CHAT_ID=${_TELEGRAM_CHAT_ID},
        ADMIN_CHAT_ID=${_ADMIN_CHAT_ID},
        TELEGRAM_WEBHOOK_SECRET=${_TELEGRAM_WEBHOOK_SECRET},
        CRON_SECRET=${_CRON_SECRET}
      # --- END OF CORRECTION ---
    waitFor: ['push-image']

  # 4) Get URL and update the service with APP_URL. This creates a new revision.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'set-app-url'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$$(gcloud run services describe telegram-reminder-bot --region=asia-southeast1 --format="value(status.url)")
        echo "Updating service with APP_URL=$$SERVICE_URL"
        gcloud run services update telegram-reminder-bot \
          --region=asia-southeast1 \
          --update-env-vars=APP_URL=$$SERVICE_URL
        echo $$SERVICE_URL > /workspace/service_url.txt
    waitFor: ['deploy-cloudrun']

  # 5) Route 100% of traffic to the LATEST revision which now has the correct APP_URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-traffic'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'telegram-reminder-bot'
      - '--to-latest'
      - '--region'
      - 'asia-southeast1'
    waitFor: ['set-app-url']

  # 6) Set Telegram Webhook
  # NOTE: Webhook setup now handled by the application on startup since secrets
  # are only available inside the Cloud Run container via Secret Manager
  - name: 'gcr.io/cloud-builders/curl'
    id: 'set-telegram-webhook'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$$(cat /workspace/service_url.txt)
        echo "📝 Service URL ready: $$SERVICE_URL"
        echo "🔗 Telegram webhook will be configured by the application on startup"
        echo "ℹ️  Bot will use APP_URL environment variable and TELEGRAM_BOT_TOKEN secret"
        echo "✅ Webhook setup delegated to application"
    waitFor: ['update-traffic']

  # 7) Health check
  - name: 'gcr.io/cloud-builders/curl'
    id: 'health-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$$(cat /workspace/service_url.txt)
        echo "🔍 Health checking: $$SERVICE_URL/health"
        echo "Waiting 30 seconds for traffic to be fully routed..."
        sleep 30
        for i in {1..5}; do
          if curl -fsS "$$SERVICE_URL/health"; then
            echo "✅ Health check passed"
            exit 0
          fi
          echo "⏳ Health check attempt $$i failed, retrying in 10s..."
          sleep 10
        done
        echo "❌ Health check failed after 5 attempts"
        exit 1
    waitFor: ['set-telegram-webhook']

# Variables for Trigger - Updated to use substitution variables
substitutions:
  # These should be configured in your Cloud Build trigger:
  # Telegram Bot Configuration
  _TELEGRAM_BOT_TOKEN: 'your_bot_token_here'
  _TELEGRAM_CHAT_ID: 'your_chat_id_here'
  _ADMIN_CHAT_ID: 'your_admin_chat_id_here'
  _TELEGRAM_WEBHOOK_SECRET: 'your_webhook_secret_here'
  _CRON_SECRET: 'your_cron_secret_here'

  # Database Configuration
  _TIDB_HOST: 'your_tidb_host_here'
  _TIDB_USER: 'your_tidb_user_here'
  _TIDB_PASSWORD: 'your_tidb_password_here'
  _TIDB_DATABASE: 'telegram_bot'
  _TIDB_PORT: '4000'
  _TIDB_ENABLE_SSL: 'true'

  # Logging Configuration
  _LOG_LEVEL: 'INFO'
  _LOG_TO_FILE: 'false'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'

timeout: '1200s'

images:
  - 'gcr.io/$PROJECT_ID/telegram-reminder-bot:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/telegram-reminder-bot:latest'

tags:
  - 'telegram-bot'
  - 'cloud-run'
  - 'production'