# Optimized scheduled reminders workflow

name: Scheduled Telegram Reminders

on:
  schedule:
    # Morning Times (in UTC, corresponding to 07:25, 08:25, 09:25 Thai time)
    - cron: '25 0 * * 1-5'
    - cron: '25 1 * * 1-5'
    - cron: '25 2 * * 1-5'
    # Afternoon Times (in UTC, corresponding to 15:30, 16:30, 17:30 Thai time)
    - cron: '30 8 * * 1-5'
    - cron: '30 9 * * 1-5'
    - cron: '30 10 * * 1-5'
  workflow_dispatch: {}

jobs:
  trigger-reminders:
    runs-on: ubuntu-latest
    name: Trigger Scheduled Reminder
    env:
      APP: ${{ secrets.CLOUD_RUN_URL }}
      TOKEN: ${{ secrets.CRON_SECRET }}

    steps:
      - name: Send POST Request to /api/cron
        run: |
          # Determine the reminder type (morning/evening) based on the cron trigger
          REMINDER_TYPE="morning"
          if [[ "${{ github.event.schedule }}" == "30 "* ]]; then
            REMINDER_TYPE="evening"
          fi
          
          # Convert UTC cron time back to Thai time for the payload
          UTC_HOUR=$(echo "${{ github.event.schedule }}" | cut -d' ' -f2)
          THAI_HOUR=$(printf %02d $(((UTC_HOUR + 7) % 24)))
          MINUTE=$(echo "${{ github.event.schedule }}" | cut -d' ' -f1)
          THAI_TIME="${THAI_HOUR}:${MINUTE}"

          echo "Triggering '$REMINDER_TYPE' reminder for Thai time: $THAI_TIME"

          # Use --fail to automatically exit with an error code if HTTP response is not 2xx
          # Use --max-time 60 to allow for Cloud Run cold starts
          curl --fail --max-time 60 -sS \
            -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"type\":\"$REMINDER_TYPE\",\"time\":\"$THAI_TIME\"}" \
            "$APP/api/cron"
