name: Scheduled Telegram Reminders

on:
  schedule:
    # Morning (Thai) -> UTC
    - cron: '25 0 * * 1-5'   # 07:25 TH = 00:25 UTC
    - cron: '25 1 * * 1-5'   # 08:25 TH = 01:25 UTC
    - cron: '25 2 * * 1-5'   # 09:25 TH = 02:25 UTC
    # Afternoon (Thai) -> UTC
    - cron: '30 8 * * 1-5'   # 15:30 TH = 08:30 UTC
    - cron: '30 9 * * 1-5'   # 16:30 TH = 09:30 UTC
    - cron: '30 10 * * 1-5'  # 17:30 TH = 10:30 UTC
  workflow_dispatch: {}

jobs:

  trigger-0725:
    if: github.event.schedule == '25 0 * * 1-5'
    runs-on: ubuntu-latest
    name: Morning (07:25 TH)
    env:
      APP: ${{ secrets.CLOUD_RUN_URL }}
      TOKEN: ${{ secrets.CRON_SECRET }}
    steps:
      - name: POST /api/cron
        run: |
          response=$(curl -s -w "%{http_code}" -o body.txt \
            -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"type":"morning","time":"07:25"}' \
            "$APP/api/cron")
          echo "HTTP: $response"; test "$response" -ge 200 -a "$response" -lt 300

  trigger-0825:
    if: github.event.schedule == '25 1 * * 1-5'
    runs-on: ubuntu-latest
    name: Morning (08:25 TH)
    env:
      APP: ${{ secrets.CLOUD_RUN_URL }}
      TOKEN: ${{ secrets.CRON_SECRET }}
    steps:
      - name: POST /api/cron
        run: |
          response=$(curl -s -w "%{http_code}" -o body.txt \
            -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"type":"morning","time":"08:25"}' \
            "$APP/api/cron")
          echo "HTTP: $response"; test "$response" -ge 200 -a "$response" -lt 300

  trigger-0925:
    if: github.event.schedule == '25 2 * * 1-5'
    runs-on: ubuntu-latest
    name: Morning (09:25 TH)
    env:
      APP: ${{ secrets.CLOUD_RUN_URL }}
      TOKEN: ${{ secrets.CRON_SECRET }}
    steps:
      - name: POST /api/cron
        run: |
          response=$(curl -s -w "%{http_code}" -o body.txt \
            -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"type":"morning","time":"09:25"}' \
            "$APP/api/cron")
          echo "HTTP: $response"; test "$response" -ge 200 -a "$response" -lt 300

  trigger-1530:
    if: github.event.schedule == '30 8 * * 1-5'
    runs-on: ubuntu-latest
    name: Afternoon (15:30 TH)
    env:
      APP: ${{ secrets.CLOUD_RUN_URL }}
      TOKEN: ${{ secrets.CRON_SECRET }}
    steps:
      - name: POST /api/cron
        run: |
          response=$(curl -s -w "%{http_code}" -o body.txt \
            -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"type":"evening","time":"15:30"}' \
            "$APP/api/cron")
          echo "HTTP: $response"; test "$response" -ge 200 -a "$response" -lt 300

  trigger-1630:
    if: github.event.schedule == '30 9 * * 1-5'
    runs-on: ubuntu-latest
    name: Afternoon (16:30 TH)
    env:
      APP: ${{ secrets.CLOUD_RUN_URL }}
      TOKEN: ${{ secrets.CRON_SECRET }}
    steps:
      - name: POST /api/cron
        run: |
          response=$(curl -s -w "%{http_code}" -o body.txt \
            -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"type":"evening","time":"16:30"}' \
            "$APP/api/cron")
          echo "HTTP: $response"; test "$response" -ge 200 -a "$response" -lt 300

  trigger-1730:
    if: github.event.schedule == '30 10 * * 1-5'
    runs-on: ubuntu-latest
    name: Afternoon (17:30 TH)
    env:
      APP: ${{ secrets.CLOUD_RUN_URL }}
      TOKEN: ${{ secrets.CRON_SECRET }}
    steps:
      - name: POST /api/cron
        run: |
          response=$(curl -s -w "%{http_code}" -o body.txt \
            -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"type":"evening","time":"17:30"}' \
            "$APP/api/cron")
          echo "HTTP: $response"; test "$response" -ge 200 -a "$response" -lt 300
