name: Scheduled Telegram Reminders

on:
  schedule:
    # Morning reminder - 7:25 AM Thai time (00:25 UTC)
    - cron: '25 0 * * 1-5'
    # Morning message - 8:25 AM Thai time (01:25 UTC)  
    - cron: '25 1 * * 1-5'
    # Evening reminder - 3:25 PM Thai time (08:25 UTC)
    - cron: '25 8 * * 1-5'
    # Evening message - 4:25 PM Thai time (09:25 UTC)
    - cron: '25 9 * * 1-5'

jobs:
  trigger-morning-reminder:
    if: github.event.schedule == '25 0 * * 1-5'
    runs-on: ubuntu-latest
    name: Morning Reminder (7:25 AM Thai)
    
    steps:
      - name: Trigger Morning Reminder
        run: |
          response=$(curl -s -w "%{http_code}" -o response_body.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"type":"morning","time":"07:25"}' \
            ${{ secrets.CLOUD_RUN_URL }}/api/cron)
          
          echo "HTTP Response Code: $response"
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Morning reminder triggered successfully"
            cat response_body.txt
          else
            echo "❌ Failed to trigger morning reminder"
            cat response_body.txt
            exit 1
          fi

      - name: Retry on failure
        if: failure()
        run: |
          echo "🔄 Retrying morning reminder..."
          sleep 30
          response=$(curl -s -w "%{http_code}" -o response_body.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"type":"morning","time":"07:25"}' \
            ${{ secrets.CLOUD_RUN_URL }}/api/cron)
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Morning reminder retry succeeded"
            cat response_body.txt
          else
            echo "❌ Morning reminder retry failed"
            cat response_body.txt
            exit 1
          fi

  trigger-afternoon-reminder:
    if: github.event.schedule == '25 1 * * 1-5'
    runs-on: ubuntu-latest
    name: Afternoon Reminder (8:25 AM Thai)
    
    steps:
      - name: Trigger Afternoon Reminder
        run: |
          response=$(curl -s -w "%{http_code}" -o response_body.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"type":"afternoon","time":"08:25"}' \
            ${{ secrets.CLOUD_RUN_URL }}/api/cron)
          
          echo "HTTP Response Code: $response"
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Afternoon reminder triggered successfully"
            cat response_body.txt
          else
            echo "❌ Failed to trigger afternoon reminder"
            cat response_body.txt
            exit 1
          fi

      - name: Retry on failure
        if: failure()
        run: |
          echo "🔄 Retrying afternoon reminder..."
          sleep 30
          response=$(curl -s -w "%{http_code}" -o response_body.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"type":"afternoon","time":"08:25"}' \
            ${{ secrets.CLOUD_RUN_URL }}/api/cron)
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Afternoon reminder retry succeeded"
            cat response_body.txt
          else
            echo "❌ Afternoon reminder retry failed"
            cat response_body.txt
            exit 1
          fi

  trigger-evening-reminder:
    if: github.event.schedule == '25 8 * * 1-5'
    runs-on: ubuntu-latest
    name: Evening Reminder (3:25 PM Thai)
    
    steps:
      - name: Trigger Evening Reminder
        run: |
          response=$(curl -s -w "%{http_code}" -o response_body.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"type":"evening","time":"15:25"}' \
            ${{ secrets.CLOUD_RUN_URL }}/api/cron)
          
          echo "HTTP Response Code: $response"
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Evening reminder triggered successfully"
            cat response_body.txt
          else
            echo "❌ Failed to trigger evening reminder"
            cat response_body.txt
            exit 1
          fi

      - name: Retry on failure
        if: failure()
        run: |
          echo "🔄 Retrying evening reminder..."
          sleep 30
          response=$(curl -s -w "%{http_code}" -o response_body.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"type":"evening","time":"15:25"}' \
            ${{ secrets.CLOUD_RUN_URL }}/api/cron)
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Evening reminder retry succeeded"
            cat response_body.txt
          else
            echo "❌ Evening reminder retry failed"
            cat response_body.txt
            exit 1
          fi

  trigger-evening-message:
    if: github.event.schedule == '25 9 * * 1-5'
    runs-on: ubuntu-latest
    name: Evening Message (4:25 PM Thai)
    
    steps:
      - name: Trigger Evening Message
        run: |
          response=$(curl -s -w "%{http_code}" -o response_body.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"type":"evening","time":"16:25"}' \
            ${{ secrets.CLOUD_RUN_URL }}/api/cron)
          
          echo "HTTP Response Code: $response"
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Evening message triggered successfully"
            cat response_body.txt
          else
            echo "❌ Failed to trigger evening message"
            cat response_body.txt
            exit 1
          fi

      - name: Retry on failure
        if: failure()
        run: |
          echo "🔄 Retrying evening message..."
          sleep 30
          response=$(curl -s -w "%{http_code}" -o response_body.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"type":"evening","time":"16:25"}' \
            ${{ secrets.CLOUD_RUN_URL }}/api/cron)
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Evening message retry succeeded"
            cat response_body.txt
          else
            echo "❌ Evening message retry failed"
            cat response_body.txt
            exit 1
          fi

  # Manual trigger for testing
  manual-trigger:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Manual Test Trigger
    
    steps:
      - name: Test Health Endpoint
        run: |
          echo "🔍 Testing Cloud Run health endpoint..."
          curl -f ${{ secrets.CLOUD_RUN_URL }}/health
          
      - name: Test Cron Endpoint Authorization
        run: |
          echo "🔍 Testing cron endpoint authorization..."
          response=$(curl -s -w "%{http_code}" -o response_body.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"type":"morning","time":"manual-test"}' \
            ${{ secrets.CLOUD_RUN_URL }}/api/cron)
          
          echo "HTTP Response Code: $response"
          cat response_body.txt

# Allow manual workflow dispatch for testing
on:
  schedule:
    - cron: '25 0 * * 1-5'
    - cron: '25 1 * * 1-5'
    - cron: '25 8 * * 1-5'
    - cron: '25 9 * * 1-5'
  workflow_dispatch: # Allow manual trigger